services:
    mariadb:
      container_name: mariadb
      networks:
        - inception
      build:
        context: requirements/mariadb
        dockerfile: Dockerfile
      volumes:
        - mariadb:/var/lib/mysql
      restart: unless-stopped
      env_file: .env
      expose:
        - "3306"

    nginx:
      container_name: nginx
      networks:
        - inception
      build:
        context: requirements/nginx 
        dockerfile: Dockerfile
      volumes:
        - wordpress:/var/www/wordpress
      restart: on-failure
      env_file: .env
      ports:
        - "443:443"
      depends_on:
        - wordpress
   
    wordpress:
      container_name: wordpress
      networks:
        - inception
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      volumes:
        - wordpress:/var/www/wordpress
      restart: on-failure
      env_file: .env
      expose:
        - "9000"
      depends_on:
        - mariadb
volumes:
    wordpress:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/thlefebv/data/wordpress'
    mariadb:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/thlefebv/data/mariadb'

networks:
    inception:
      driver: bridge
      name: inception
